Repository scalecube/scalecube-cluster, pull requests merged in 2019-01, with the labels that each got.

#155 update version of jackson-databind due to security alert
  pom.xml
Labels: Security

#156 Quick release: update version of jackson-databind due to security alert
  pom.xml
Labels: Security

#154 Use Transport.requestResponse()
  cluster/src/main/java/io/scalecube/cluster/ClusterImpl.java
  cluster/src/main/java/io/scalecube/cluster/CorrelationIdGenerator.java
  cluster/src/main/java/io/scalecube/cluster/fdetector/FailureDetectorImpl.java
  cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocolImpl.java
  cluster/src/main/java/io/scalecube/cluster/metadata/MetadataStoreImpl.java
  cluster/src/test/java/io/scalecube/cluster/ClusterTest.java
  cluster/src/test/java/io/scalecube/cluster/membership/MembershipProtocolTest.java
  transport/src/main/java/io/scalecube/transport/Transport.java
  transport/src/main/java/io/scalecube/transport/TransportImpl.java
Labels: enhancement, ready for review

#163 Changed work with period in FailureDetectorImpl and GossipProtocolImpl
  cluster/src/main/java/io/scalecube/cluster/fdetector/FailureDetectorImpl.java
  cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java
Labels: ready for review
